# Generated by Django 3.0.10 on 2020-10-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20201005_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='faculty',
        ),
    ]
