# Generated by Django 3.0.10 on 2020-09-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20200929_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='acronym',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
