# Generated by Django 3.0.10 on 2020-09-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20200929_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='active_status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=10),
        ),
    ]
