# Generated by Django 3.0.10 on 2020-11-02 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20201102_1234'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('depreciation', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Purchase Date')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('qr_code_key', models.CharField(blank=True, max_length=200, null=True)),
                ('rf_id_key', models.CharField(blank=True, max_length=200, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('warranty_type', models.CharField(choices=[('year', 'Year')], max_length=10)),
                ('warranty_date', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='traceableitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='traceableitem',
            name='department',
        ),
        migrations.RemoveField(
            model_name='traceableitem',
            name='location',
        ),
        migrations.RemoveField(
            model_name='traceableitem',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='traceableitem',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='traceableitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='traceableitem',
            name='resp_emp',
        ),
        migrations.RemoveField(
            model_name='traceableitem',
            name='status',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='itemassign',
            name='assigned_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemassign',
            name='assigned_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Location', verbose_name='Assigned Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='memo',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='memos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memo',
            name='tender',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personalloan',
            name='to_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/image.png', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='property',
            name='value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='repair',
            name='res_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='NonTraceableItem',
        ),
        migrations.AddField(
            model_name='productitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Category'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Department', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='memo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Memo', verbose_name='Memo'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.ProductItem'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='resp_emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='productitem',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='products.Status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='itemassign',
            name='product_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductItem'),
        ),
        migrations.AlterField(
            model_name='personalloanitem',
            name='product_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductItem'),
        ),
        migrations.AlterField(
            model_name='repairitem',
            name='product_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.ProductItem'),
        ),
        migrations.DeleteModel(
            name='TraceableItem',
        ),
    ]
