# Generated by Django 3.0.10 on 2020-10-06 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201005_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nontraceableitem',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.NonTraceableItem'),
        ),
        migrations.AlterField(
            model_name='traceableitem',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.TraceableItem'),
        ),
    ]
