# Generated by Django 3.0.10 on 2020-11-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201102_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='warranty_type',
            field=models.CharField(blank=True, choices=[('year', 'Year')], max_length=10, null=True),
        ),
    ]
