# Generated by Django 3.0.10 on 2020-11-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201102_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='product_item_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='serial_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='qr_code_key',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code/'),
        ),
    ]
